import './sass/main.scss';
import './js/components/search';
import './js/components/home';
import './js/components/pages';
import './js/components/modal';
import './js/components/library';
import './js/components/back-to-top';
import './js/components/theme';
import './js/components/footer-modal.js';
